name: test

dependencies:
  mysql1: ^0.17.1

  flutter:
    sdk: flutter

  http_server: ^0.9.8+3


version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter